import Link from "next/link";
import { ArrowDownRight, ArrowRight, BriefcaseBusiness, CalendarClock, CheckCircle2, Clock3, HardHat, MessageSquareWarning, TriangleAlert } from "lucide-react";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { ProgressBar } from "@/components/progress-bar";
import { StatusBadge } from "@/components/status-badge";
import { daysUntil, shortDate } from "@/lib/format";
import { projectService } from "@/services/project-service";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const { projects, issues, updates } = await projectService.getDashboardData();
  const openIssues = issues.filter((issue) => issue.status !== "Resolvida");
  const today = new Date().toISOString().slice(0, 10);
  const lateStages = projects.flatMap((project) => project.stages.filter((stage) => stage.status === "Atrasado").map((stage) => ({ ...stage, project })));
  const attention = projects.map((project) => {
    const projectIssues = openIssues.filter((issue) => issue.projectId === project.id);
    const deliverySoonAndBehind = daysUntil(project.due) >= 0 && daysUntil(project.due) <= 30 && project.progress < 80;
    const reasons = [project.status === "Atrasado" && "Projeto atrasado", project.status === "Atenção" && "Projeto em atenção", project.stages.some((stage) => stage.status === "Bloqueado") && "Etapa bloqueada", project.stages.some((stage) => stage.status === "Atrasado") && "Etapa atrasada", projectIssues.some((issue) => issue.priority === "Crítica") && "Pendência crítica", projectIssues.some((issue) => issue.status === "Aguardando terceiro") && "Aguardando terceiro", projectIssues.some((issue) => issue.due && issue.due < today) && "Pendência vencida", deliverySoonAndBehind && "Entrega próxima com progresso abaixo do esperado"];
    return { project, projectIssues, reason: reasons.filter(Boolean)[0] };
  }).filter((item) => item.reason).sort((a, b) => Number(b.project.status === "Atrasado") - Number(a.project.status === "Atrasado"));
  const milestones = [
    ...projects.flatMap((project) => project.stages.filter((stage) => stage.end >= today && stage.end <= new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10) && stage.status !== "Concluído").map((stage) => ({ key: `stage-${stage.id}`, title: stage.name, project: project.name, date: stage.end, detail: `${stage.progress}% · ${stage.status}`, href: `/projects/${project.id}#stages` }))),
    ...projects.filter((project) => project.due >= today && project.due <= new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10) && project.status !== "Concluído").map((project) => ({ key: `project-${project.id}`, title: "Entrega prevista", project: project.name, date: project.due, detail: `${project.progress}% de progresso`, href: `/projects/${project.id}` })),
    ...openIssues.filter((issue) => issue.due >= today && issue.due <= new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10) && ["Alta", "Crítica"].includes(issue.priority)).map((issue) => ({ key: `issue-${issue.id}`, title: issue.title, project: projects.find((project) => project.id === issue.projectId)?.name ?? "Projeto", date: issue.due, detail: `${issue.priority} · ${issue.status}`, href: `/projects/${issue.projectId}#issues` })),
  ].sort((a, b) => a.date.localeCompare(b.date)).slice(0, 6);
  const allStages = projects.flatMap((project) => project.stages);
  const averageProgress = projects.length ? Math.round(projects.reduce((sum, project) => sum + project.progress, 0) / projects.length) : 0;
  const nearDelivery = projects.filter((project) => daysUntil(project.due) >= 0 && daysUntil(project.due) <= 30 && project.status !== "Concluído").length;
  return <>
    <PageHeader title="Visão geral" description="Acompanhe o andamento físico das obras, identifique desvios e mantenha as equipes alinhadas." />
    <div className="mb-6 flex items-center justify-between rounded-lg border border-[#dcebe1] bg-[#f0f7f2] px-4 py-3"><div className="flex items-center gap-2.5"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-forest"><BriefcaseBusiness size={14} /></div><div><p className="text-xs font-semibold text-[#285c45]">Portfólio em acompanhamento</p><p className="mt-0.5 text-[11px] text-[#4f6b5a]">{projects.length} projetos · dados operacionais do Supabase</p></div></div><span className="hidden rounded-full bg-white px-2.5 py-1 text-[10px] font-medium text-[#4f6b5a] sm:inline-flex">DADOS FICTÍCIOS</span></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-4"><MetricCard label="Projetos ativos" value={String(projects.filter((project) => !["Concluído", "Planejamento"].includes(project.status)).length)} note={`${projects.filter((project) => project.status === "Planejamento").length} em planejamento`} icon={<BriefcaseBusiness size={16} />} /><MetricCard label="Projetos atrasados" value={String(projects.filter((project) => project.status === "Atrasado").length)} note={`${attention.length} exigem atenção`} tone="red" icon={<TriangleAlert size={16} />} /><MetricCard label="Progresso físico médio" value={`${averageProgress}%`} note="Média do portfólio" tone="blue" icon={<CheckCircle2 size={16} />} /><MetricCard label="Próximas entregas" value={String(nearDelivery)} note="Nos próximos 30 dias" tone="amber" icon={<CalendarClock size={16} />} /></div>
    <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-4"><div className="rounded-lg border border-line bg-white px-4 py-3.5 shadow-soft"><div className="flex items-center justify-between text-[11px] text-slate-500"><span>Pendências abertas</span><MessageSquareWarning size={15} /></div><div className="mt-1.5 text-lg font-semibold">{openIssues.length}<span className="ml-2 text-[10px] font-normal text-slate-500">no portfólio</span></div></div><div className="rounded-lg border border-line bg-white px-4 py-3.5 shadow-soft"><div className="flex items-center justify-between text-[11px] text-slate-500"><span>Pendências críticas</span><TriangleAlert size={15} className="text-rose-600" /></div><div className="mt-1.5 text-lg font-semibold">{openIssues.filter((issue) => issue.priority === "Crítica").length}<span className="ml-2 text-[10px] font-normal text-rose-600">atenção imediata</span></div></div><div className="rounded-lg border border-line bg-white px-4 py-3.5 shadow-soft"><div className="flex items-center justify-between text-[11px] text-slate-500"><span>Etapas atrasadas</span><Clock3 size={15} className="text-amber-600" /></div><div className="mt-1.5 text-lg font-semibold">{lateStages.length}<span className="ml-2 text-[10px] font-normal text-slate-500">em {new Set(lateStages.map((stage) => stage.project.id)).size} projetos</span></div></div><div className="rounded-lg border border-line bg-white px-4 py-3.5 shadow-soft"><div className="flex items-center justify-between text-[11px] text-slate-500"><span>Aguardando terceiros</span><HardHat size={15} /></div><div className="mt-1.5 text-lg font-semibold">{openIssues.filter((issue) => issue.status === "Aguardando terceiro").length}<span className="ml-2 text-[10px] font-normal text-slate-500">pendências abertas</span></div></div></div>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(310px,1fr)]"><section className="min-w-0 overflow-hidden rounded-lg border border-line bg-white shadow-soft"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Projetos que exigem atenção</h2><p className="mt-1 text-[11px] text-muted">Atrasos, bloqueios e pendências prioritárias</p></div><Link href="/projects" className="inline-flex items-center gap-1 text-xs font-medium text-forest hover:text-emerald-800">Ver projetos <ArrowRight size={14} /></Link></div>{attention.map(({ project, projectIssues, reason }, index) => { const mainIssue = projectIssues.find((issue) => issue.priority === "Crítica") ?? projectIssues.find((issue) => issue.due && issue.due < today) ?? projectIssues[0]; return <div key={project.id} className={`grid gap-3 px-5 py-4 sm:grid-cols-[minmax(0,1.3fr)_105px_110px] sm:items-center ${index ? "border-t border-line" : ""}`}><div className="min-w-0"><Link href={`/projects/${project.id}`} className="block truncate text-[13px] font-semibold text-ink hover:text-forest">{project.name}</Link><div className="mt-1 text-[11px] text-slate-500">{project.unit} · {project.city} · {project.owner}</div><div className="mt-3 max-w-[260px]"><ProgressBar value={project.progress} compact /></div></div><div className="flex items-center justify-between gap-2 sm:block"><div className="mb-1 text-[10px] text-slate-500">Status</div><StatusBadge status={project.status} /></div><div className="flex items-center justify-between gap-2 sm:block"><div className="mb-1 text-[10px] text-slate-500">Prazo</div><div className="text-xs font-medium">{shortDate(project.due)}</div></div><div className="rounded-md bg-slate-50 px-3 py-2 text-[11px] text-slate-600 sm:col-span-3"><span className="mr-1.5 font-medium text-slate-800">{reason}</span>{mainIssue ? `· ${mainIssue.title}` : ""}<span className="ml-1.5 text-slate-500">· {projectIssues.length} pendências abertas</span></div></div>; })}{attention.length === 0 && <p className="px-5 py-8 text-xs text-slate-500">Nenhum projeto exige atenção neste momento.</p>}</section>
      <section className="min-w-0 rounded-lg border border-line bg-white shadow-soft"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Próximos marcos</h2><p className="mt-1 text-[11px] text-muted">Etapas, entregas e pendências importantes</p></div><CalendarClock size={16} className="text-slate-500" /></div><div className="divide-y divide-line">{milestones.map((milestone) => <Link key={milestone.key} href={milestone.href} className="flex items-start gap-3 px-5 py-3.5 hover:bg-slate-50"><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-[#eef5f0] text-forest"><ArrowDownRight size={14} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{milestone.title}</div><div className="mt-1 truncate text-[10px] text-slate-500">{milestone.project} · {milestone.detail}</div></div><div className="shrink-0 text-right"><div className="text-[11px] font-medium">{shortDate(milestone.date)}</div></div></Link>)}{milestones.length === 0 && <p className="px-5 py-8 text-xs text-slate-500">Nenhum marco futuro nos próximos 30 dias.</p>}</div></section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(310px,1fr)]"><section className="rounded-lg border border-line bg-white shadow-soft"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Andamento do portfólio</h2><p className="mt-1 text-[11px] text-muted">Progresso geral por projeto</p></div><Link href="/projects" className="text-xs font-medium text-forest">Abrir lista <ArrowRight size={13} className="ml-1 inline" /></Link></div><div className="divide-y divide-line">{projects.map((project) => <div key={project.id} className="grid grid-cols-[minmax(0,1fr)_100px] items-center gap-x-4 gap-y-2 px-5 py-3.5 sm:grid-cols-[minmax(0,1.2fr)_minmax(150px,.8fr)_90px]"><Link href={`/projects/${project.id}`} className="min-w-0 truncate text-xs font-medium hover:text-forest">{project.name}<span className="mt-1 block truncate text-[10px] font-normal text-slate-500">{project.unit} · {project.city}</span></Link><div className="col-span-2 sm:col-span-1"><ProgressBar value={project.progress} /></div><div className="justify-self-end"><StatusBadge status={project.status} /></div></div>)}</div></section><section className="rounded-lg border border-line bg-white shadow-soft"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Últimas atualizações</h2><p className="mt-1 text-[11px] text-muted">Registros recentes das equipes</p></div><Link href="/updates" className="text-xs font-medium text-forest">Ver todas <ArrowRight size={13} className="ml-1 inline" /></Link></div><div className="divide-y divide-line">{updates.slice(0, 4).map((update) => <div key={update.id} className="px-5 py-3.5"><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-semibold">{update.projectName}</span><span className="shrink-0 text-[10px] text-slate-400">{shortDate(update.date.slice(0, 10))}</span></div><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-slate-600">{update.text}</p></div>)}{updates.length === 0 && <p className="px-5 py-8 text-xs text-slate-500">Nenhuma atualização registrada.</p>}</div></section></div>
    <section aria-label="Resumo operacional" className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{[{ label: "Projetos em atenção", value: attention.length }, { label: "Etapas concluídas", value: allStages.filter((stage) => stage.status === "Concluído").length }, { label: "Etapas em andamento", value: allStages.filter((stage) => stage.status === "Em andamento").length }, { label: "Etapas bloqueadas", value: allStages.filter((stage) => stage.status === "Bloqueado").length }, { label: "Pendências vencidas", value: openIssues.filter((issue) => issue.due && issue.due < today).length }].map((metric) => <div key={metric.label} className="rounded-lg border border-line bg-white px-4 py-3 shadow-soft"><div className="text-[11px] text-slate-500">{metric.label}</div><div className="mt-1 text-lg font-semibold">{metric.value}</div></div>)}</section>
  </>;
}
