"use client";

import { useMemo, useState } from "react";
import { FileArchive, FileSpreadsheet, FileText, FolderOpen, Image, Search } from "lucide-react";
import type { DocumentItem, Project } from "@/types";

const categories = ["Todos", "Projeto", "Orçamento", "Contrato", "Planta", "Foto", "Laudo", "Outro"];
const iconFor = (kind: string) => kind === "XLSX" ? FileSpreadsheet : kind === "JPG" ? Image : kind === "ZIP" ? FileArchive : FileText;

export function DocumentsBrowser({ documents, projects }: { documents: DocumentItem[]; projects: Project[] }) {
  const [category, setCategory] = useState("Todos"); const [query, setQuery] = useState("");
  const filtered = useMemo(() => documents.filter((item) => (category === "Todos" || item.category === category) && `${item.name} ${item.category} ${projects.find((p) => p.id === item.projectId)?.name ?? ""}`.toLowerCase().includes(query.toLowerCase())), [documents, projects, category, query]);
  return <><div className="rounded-lg border border-line bg-white p-3 shadow-soft sm:p-4"><label className="flex h-10 items-center gap-2.5 rounded-md border border-line px-3 text-slate-400"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-xs text-ink outline-none placeholder:text-slate-400" placeholder="Buscar documento ou projeto" /></label><div className="mt-3 flex gap-2 overflow-x-auto">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-[11px] font-medium ${category === item ? "bg-[#e7f1ea] text-forest" : "bg-slate-100 text-slate-500 hover:bg-slate-200"}`}>{item}</button>)}</div></div><div className="mb-3 mt-4 px-1 text-[11px] text-slate-500">{filtered.length} documentos</div>{filtered.length ? <div className="overflow-hidden rounded-lg border border-line bg-white shadow-soft"><div className="hidden grid-cols-[minmax(0,1.6fr)_minmax(150px,1fr)_110px_90px] border-b border-line bg-slate-50/80 px-5 py-3 text-[10px] font-semibold uppercase tracking-wider text-slate-500 sm:grid"><span>Documento</span><span>Projeto</span><span>Atualizado</span><span>Tamanho</span></div><div className="divide-y divide-line">{filtered.map((item) => { const Icon = iconFor(item.kind); const project = projects.find((entry) => entry.id === item.projectId); return <div key={item.id} className="grid gap-2 px-4 py-3.5 sm:grid-cols-[minmax(0,1.6fr)_minmax(150px,1fr)_110px_90px] sm:items-center sm:px-5"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-slate-100 text-slate-500"><Icon size={16} /></div><div className="min-w-0"><div className="truncate text-xs font-medium">{item.name}</div><div className="mt-1 text-[10px] text-slate-400">{item.category} · {item.kind}</div>{(item.stage || item.author) && <div className="mt-0.5 truncate text-[10px] text-slate-400">{item.stage}{item.stage && item.author ? " · " : ""}{item.author}</div>}</div></div><div className="pl-12 text-[11px] text-slate-600 sm:pl-0">{project?.name}</div><div className="hidden text-[11px] text-slate-500 sm:block">{new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${item.updatedAt}T12:00:00`))}</div><div className="hidden text-[11px] text-slate-500 sm:block">{item.size}</div></div>; })}</div></div> : <div className="rounded-lg border border-dashed border-slate-300 bg-white p-12 text-center"><FolderOpen className="mx-auto text-slate-300" size={28} /><h2 className="mt-3 text-sm font-semibold">Nenhum documento nesta categoria</h2><p className="mt-1 text-xs text-slate-500">Os documentos desta categoria aparecerão aqui quando cadastrados.</p></div>}<p className="mt-4 text-[10px] text-slate-400">Os metadados dos arquivos são demonstrativos; o armazenamento de arquivos não está ativo.</p></>;
}
