import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, Check, Clock3, FileText, HardHat, MapPin, MessageSquare, Paperclip, UserRound } from "lucide-react";
import { ProgressBar } from "@/components/progress-bar";
import { StatusBadge } from "@/components/status-badge";
import { StageEditor } from "@/components/stage-editor";
import { daysUntil, fullDate, shortDate } from "@/lib/format";
import { projectService } from "@/services/project-service";

export const dynamic = "force-dynamic";
const tabs = [{ id: "overview", label: "Visão geral" }, { id: "stages", label: "Etapas" }, { id: "issues", label: "Pendências" }, { id: "contractors", label: "Terceirizados" }, { id: "updates", label: "Atualizações" }, { id: "documents", label: "Documentos" }];

export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await projectService.getProject(id);
  if (!data) notFound();
  const { project, issues, updates, documents, contractors } = data;
  const projectIssues = issues.filter((issue) => issue.status !== "Resolvida");
  const completedStages = project.stages.filter((stage) => stage.status === "Concluído").length;
  const activeStages = project.stages.filter((stage) => stage.status === "Em andamento").length;
  const lateStages = project.stages.filter((stage) => stage.status === "Atrasado").length;
  const remaining = daysUntil(project.due); const elapsed = project.start ? Math.max(0, -daysUntil(project.start)) : 0;
  return <>
    <div className="mb-5"><Link href="/projects" className="inline-flex items-center gap-1.5 text-xs text-slate-500 hover:text-forest"><ArrowLeft size={14} /> Voltar aos projetos</Link></div>
    <section className="rounded-lg border border-line bg-white p-5 shadow-soft sm:p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><StatusBadge status={project.status} /><span className="text-[11px] text-slate-400">{project.type}</span></div><h1 className="text-xl font-semibold tracking-tight sm:text-[26px]">{project.name}</h1><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><MapPin size={13} />{project.unit} · {project.city}</span><span className="inline-flex items-center gap-1"><UserRound size={13} />{project.owner}</span><span className="inline-flex items-center gap-1"><CalendarDays size={13} />Entrega prevista {fullDate(project.due)}</span></div></div><div className="w-full max-w-sm"><div className="mb-1.5 flex justify-between text-[11px]"><span className="font-medium text-slate-600">Progresso físico</span><span className="font-semibold text-forest">{project.progress}%</span></div><ProgressBar value={project.progress} /></div></div><div className="mt-6 grid grid-cols-2 gap-3 border-t border-line pt-5 sm:grid-cols-4 xl:grid-cols-7">{[{ label: "Dias decorridos", value: `${elapsed} dias`, icon: <Clock3 size={14} /> }, { label: "Dias restantes", value: `${remaining} dias`, icon: <CalendarDays size={14} /> }, { label: "Etapas concluídas", value: String(completedStages), icon: <Check size={14} /> }, { label: "Etapas em andamento", value: String(activeStages), icon: <Clock3 size={14} /> }, { label: "Etapas atrasadas", value: String(lateStages), icon: <Clock3 size={14} /> }, { label: "Pendências abertas", value: String(projectIssues.length), icon: <MessageSquare size={14} /> }, { label: "Terceirizados", value: String(contractors.length), icon: <HardHat size={14} /> }].map((metric) => <div key={metric.label} className="min-w-0"><div className="flex items-center gap-1.5 text-[10px] text-slate-400">{metric.icon}{metric.label}</div><div className="mt-1.5 truncate text-sm font-semibold">{metric.value}</div></div>)}</div></section>
    <nav aria-label="Abas do projeto" className="sticky top-[64px] z-10 -mx-4 mt-5 overflow-x-auto border-b border-line bg-canvas px-4 sm:-mx-7 sm:px-7"><div className="flex min-w-max gap-6">{tabs.map((tab) => <a key={tab.id} href={`#${tab.id}`} className="border-b-2 border-transparent py-3 text-xs font-medium text-slate-500 hover:border-forest hover:text-forest">{tab.label}</a>)}</div></nav>
    <div className="mt-5 grid items-start gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(290px,.8fr)]"><div className="space-y-5"><section id="overview" className="scroll-mt-36 rounded-lg border border-line bg-white p-5 shadow-soft"><h2 className="text-sm font-semibold">Visão geral</h2><p className="mt-2 text-xs leading-5 text-slate-600">{project.summary}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-md bg-slate-50 p-3"><div className="text-[10px] text-slate-400">Início do projeto</div><div className="mt-1 text-xs font-medium">{fullDate(project.start)}</div></div><div className="rounded-md bg-slate-50 p-3"><div className="text-[10px] text-slate-400">Entrega prevista</div><div className="mt-1 text-xs font-medium">{fullDate(project.due)}</div></div></div></section>
      <section id="stages" className="scroll-mt-36 rounded-lg border border-line bg-white shadow-soft"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Etapas do projeto</h2><p className="mt-1 text-[11px] text-slate-500">Cronograma e responsáveis</p></div><span className="text-[11px] text-slate-500">{completedStages}/{project.stages.length} concluídas</span></div><div className="divide-y divide-line">{project.stages.map((stage, index) => <div key={stage.id} className="grid grid-cols-[24px_minmax(0,1fr)] gap-3 px-5 py-3.5 sm:grid-cols-[24px_minmax(0,1fr)_105px]"><div className="relative flex justify-center"><div className={`z-[1] flex h-6 w-6 items-center justify-center rounded-full ${stage.status === "Concluído" ? "bg-emerald-100 text-forest" : stage.status === "Atrasado" || stage.status === "Bloqueado" ? "bg-rose-100 text-rose-700" : stage.progress ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-400"}`}>{stage.status === "Concluído" ? <Check size={13} /> : <span className="text-[9px] font-semibold">{index + 1}</span>}</div>{index < project.stages.length - 1 && <div className="absolute top-6 h-full w-px bg-slate-200" />}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold">{stage.name}</span><StatusBadge status={stage.status} /></div><div className="mt-1.5 text-[10px] text-slate-500">{shortDate(stage.start)} – {shortDate(stage.end)} · {stage.owner}{stage.contractor && <> · {stage.contractor}</>}</div>{stage.actualStart && <div className="mt-1 text-[10px] text-slate-400">Início real {shortDate(stage.actualStart)}{stage.actualEnd ? ` · conclusão real ${shortDate(stage.actualEnd)}` : ""}</div>}{stage.note && <p className="mt-1.5 text-[10px] text-rose-600">{stage.note}</p>}<div className="mt-2 flex flex-wrap items-center gap-3"><div className="w-full max-w-[240px]"><ProgressBar value={stage.progress} compact /></div><StageEditor stage={stage} /></div></div><div className="hidden text-right sm:block"><div className="text-[10px] text-slate-400">Previsto até</div><div className="mt-1 text-[11px] font-medium">{shortDate(stage.end)}</div></div></div>)}</div>{project.stages.length === 0 && <p className="p-5 text-xs text-slate-500">Nenhuma etapa cadastrada.</p>}</section>
      <section id="issues" className="scroll-mt-36 rounded-lg border border-line bg-white shadow-soft"><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Pendências</h2></div><div className="divide-y divide-line">{issues.length ? issues.map((issue) => <div key={issue.id} className="flex flex-col justify-between gap-2 px-5 py-3 sm:flex-row sm:items-center"><div><div className="text-xs font-medium">{issue.title}</div><div className="mt-1 text-[10px] text-slate-500">{issue.stage} · {issue.owner}{issue.contractor ? ` · ${issue.contractor}` : ""}</div>{issue.description && <p className="mt-1 text-[10px] text-slate-500">{issue.description}</p>}</div><div className="flex items-center gap-2"><StatusBadge status={issue.priority} /><StatusBadge status={issue.status} /></div></div>) : <p className="p-5 text-xs text-slate-500">Nenhuma pendência vinculada.</p>}</div></section></div>
      <aside aria-label="Informações complementares do projeto" className="space-y-5"><section id="contractors" className="scroll-mt-36 rounded-lg border border-line bg-white shadow-soft"><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Terceirizados envolvidos</h2></div><div className="divide-y divide-line">{contractors.map((contractor) => { const relation = contractor.projects.find((item) => item.projectId === project.id); return <div key={contractor.id} className="px-5 py-3.5"><div className="text-xs font-semibold">{contractor.name}</div><div className="mt-1 text-[10px] text-slate-500">{contractor.specialty}</div><div className="mt-2 text-[10px] text-slate-600">Escopo: {relation?.scope ?? "Serviços técnicos"}</div><div className="mt-1 text-[10px] text-slate-500">{relation?.stageNames.join(" · ") || "Sem etapa relacionada"} · prazo {shortDate(relation?.end ?? "")}</div><div className="mt-1 text-[10px] text-slate-500">{contractor.openActivities} atividades abertas</div></div>; })}{contractors.length === 0 && <p className="p-5 text-xs text-slate-500">Nenhum terceirizado vinculado.</p>}</div></section>
        <section id="updates" className="scroll-mt-36 rounded-lg border border-line bg-white shadow-soft"><div className="flex items-center justify-between border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Atualizações</h2><Link href="/updates" className="text-[11px] font-medium text-forest">Adicionar</Link></div><div className="divide-y divide-line">{updates.length ? updates.map((update) => <div key={update.id} className="px-5 py-3.5"><div className="flex justify-between gap-3"><span className="text-[11px] font-semibold">{update.author}</span><span className="shrink-0 text-[10px] text-slate-400">{shortDate(update.date.slice(0, 10))}</span></div><p className="mt-1.5 text-[11px] leading-4 text-slate-600">{update.text}</p><div className="mt-2 flex items-center gap-3 text-[10px] text-slate-400"><span>{update.stage}</span>{update.progress !== undefined && <span>{update.progress}% progresso</span>}{update.photos > 0 && <span className="inline-flex items-center gap-1"><Paperclip size={11} /> {update.photos} fotos</span>}</div></div>) : <p className="p-5 text-xs text-slate-500">Nenhuma atualização registrada.</p>}</div></section>
        <section id="documents" className="scroll-mt-36 rounded-lg border border-line bg-white shadow-soft"><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Documentos recentes</h2></div><div className="divide-y divide-line">{documents.length ? documents.map((doc) => <div key={doc.id} className="flex items-center gap-2.5 px-5 py-3"><div className="flex h-8 w-8 items-center justify-center rounded bg-slate-100 text-slate-500"><FileText size={15} /></div><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-medium">{doc.name}</div><div className="mt-0.5 text-[10px] text-slate-400">{doc.category}{doc.stage ? ` · ${doc.stage}` : ""} · {doc.size}</div></div><span className="text-[9px] text-slate-400">{doc.kind}</span></div>) : <p className="p-5 text-xs text-slate-500">Nenhum documento anexado.</p>}</div></section></aside></div>
  </>;
}
